<?php
/**
 * Copyright © Vnecoms, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Vnecoms\VendorsMessage\Block\Vendors\Messages\View $block */
?>
<div class="row">
    <div class="col-md-3 message-folders">
        <?php echo $block->getChildHtml('folders')?>
    </div>
    <div class="col-md-9 view-message">
        <div class="message-buttons">
            <button class="btn btn-default btn-flat" onclick="setLocation('<?php echo $block->getBackUrl();?>')"><i class="fa fa-fw fa-angle-left"></i> <?php echo __("Back")?></button>
            <button class="btn btn-default btn-flat pull-right" onclick="setLocation('<?php echo $block->getDeleteUrl();?>')"><i class="fa fa-fw fa-trash-o"></i> <?php echo __("Delete")?></button>
            <!--<button class="btn btn-default btn-flat pull-right" id="msg-reply-btn"><i class="fa fa-fw fa-reply"></i><?php /*echo __("Reply")*/?></button>-->
        </div>
        <div id="vendor-messages-wrap" data-bind="scope: 'vendor-messages'">
            <div id="message-loader" data-role="message-loader" class="loading-mask" data-mage-init='{"messageLoader": {}}'>
                <div class="loader">
                    <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                         alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                         style="position: absolute;">
                </div>
            </div>
            <!-- ko template: getTemplate() --><!-- /ko -->
            <script type="text/x-magento-init">
            {
                "#vendor-messages-wrap": {
                    "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout(); ?>
                }
            }
        </script>
        </div>
    </div>
</div>
<div class="message-notification-box hide" id="vnecoms-msg-notification"><?php echo __("Sending ...")?></div>
<script>
    //<![CDATA[
    window.tinyMCE_GZ = window.tinyMCE_GZ || {}; window.tinyMCE_GZ.loaded = true;
    //]]>
</script>
