<li data-bind="scope: 'vendor-message'" id="knockout-message-header">
    <a href="<?php echo $block->getMessageUrl()?>" class="wishlist-icon link wishlist"><i class="message-icon-envelope"></i></a>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#knockout-message-header": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "vendor-message": {
                            "component": "Vnecoms_VendorsMessage/js/message/count",
                            "messageUrl": "<?= $block->getMessageUrl(); ?>",
                            "countUrl": "<?= $block->escapeUrl($block->getUrl("customer/message/count")); ?>"
                        }
                    }
                }
            }
        }
     </script>
</li>

