
<?php $_message = $block->getMessage();?>
<div class="row">
    <div class="col-md-9 view-message ">
        <div class="page-actions">
            <div class="message-buttons page-actions-buttons">
                <button id="back" title="Back" type="button"
                        class="action-default scalable back"
                        onclick="setLocation('<?php echo $block->getBackUrl() ?>')" data-ui-id="vendors-group-edit-back-button">
                    <span><?php echo __("Back") ?></span>
                </button>
            </div>
        </div>

        <div id="admin-messages-wrap" data-bind="scope: 'admin-messages'">
            <div id="message-loader" data-role="message-loader" class="loading-mask" data-mage-init='{"messageLoader": {}}'>
                <div class="loader">
                    <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                         alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                         style="position: absolute;">
                </div>
            </div>
            <!-- ko template: getTemplate() --><!-- /ko -->
            <script type="text/x-magento-init">
            {
                "#admin-messages-wrap": {
                    "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout(); ?>
                }
            }
        </script>
        </div>

    </div>
</div>


<script type="text/javascript">
    //<![CDATA[
    window.tinyMCE_GZ = window.tinyMCE_GZ || {}; window.tinyMCE_GZ.loaded = true;
    require([
        "jquery",
        "Magento_Ui/js/modal/alert",
        "mage/translate",
        "Vnecoms_VendorsMessage/js/wysiwyg/tiny_mce/setup",
    ], function(jQuery, alert, $t){

        window.buttons_top_offset = jQuery(".message-buttons").offset().top;

        function toggleFixedButtons(){
            if (jQuery(window).scrollTop() > window.buttons_top_offset) {
                jQuery('.message-buttons-footer').removeClass('hide');
            } else {
                jQuery('.message-buttons-footer').addClass('hide');
            }
        }

        jQuery(window).bind('scroll', function () {
            toggleFixedButtons();
        });
        toggleFixedButtons();
    });
    //]]>
</script>