<?php

// $vendor = $block->getVendor();

// $logo = $vendor->getData('upload_logo');

// $mediaUrl = $block->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);

$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$vendor = $block->getVendor();

$logo = $vendor->getData('upload_logo');?>
<?php if ($logo): ?>

    <img
        class="profile-user-img img-responsive img-circle"
        src="<?= $mediaUrl . $logo ?>"
        alt="Vendor Logo"
    />

<?php else: ?>

    <img
        class="profile-user-img img-responsive img-circle"
        src="<?= $block->getLogoUrl() ?>"
    />

<?php endif; ?>