<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);

$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$vendor = $block->getVendor();

$company = $vendor->getData('b_name');?>

<h3 class="profile-username text-center"><?php echo $company?></h3>