<?php
/** @var \Magento\Framework\View\Element\Template $block */

$placeholder = $block->escapeUrl(
    $block->getViewFileUrl('Magento_Catalog::images/product/placeholder/thumbnail.jpg')
);
?>

<script type="text/html" id="magento_catalog_product">
    <a rel="noreferrer"
       class="search-autocomplete-panel__row search-autocomplete-panel__row--product"
       data-bind="attr: { href: url, 'aria-label': '<?= $block->escapeJs(__('View product details: ')) ?>' + name }"
    >
        <!-- ko if: $parents[2].config.isShowImage -->
        <span class="search-autocomplete-panel__thumb">
            <img data-bind="attr: { src: (imageUrl ? imageUrl : '<?= $placeholder ?>'), alt: '<?= $block->escapeJs(__('Product image: ')) ?>' + name }"
                 />
        </span>
        <!-- /ko -->

        <span class="search-autocomplete-panel__content">
            <span class="search-autocomplete-panel__title" data-bind="html: name, highlight"></span>
            <!-- ko if: description || sku -->
            <span class="search-autocomplete-panel__subtitle" data-bind="text: description || sku, highlight"></span>
            <!-- /ko -->
        </span>
    </a>
</script>
