<div style="color:red;">🔥 Template HIT: vnecoms_vendors</div>
<script type="text/html" id="vnecoms_vendors">
    <li class="mst-search__item">
        <a data-bind="attr: { href: url }">
              <span style="color:red;">✅ Template Loaded</span>
            <span class="vendor-title" data-bind="text: title"></span>
            <div class="vendor-detail" data-bind="text: detail"></div>
        </a>
    </li>
</script>
