<?php
/**
 * Copyright © Vnecoms, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Vnecoms\VendorsMessage\Block\Customer\Account\Message\View $block */
?>
<div class="message-notification-box hide" id="vnecoms-msg-notification"><?php echo __("Sending ...")?></div>
<div class="vnecoms-message-container">
    <div class="message-buttons">
        <button class="btn btn-default btn-flat" onclick="setLocation('<?php echo $block->getBackUrl();?>')"><i class="message-icon-back"></i> <?php echo __("Back")?></button>
        <button class="btn btn-default btn-flat pull-right" onclick="setLocation('<?php echo $block->getDeleteUrl();?>')"><i class="message-icon-trash"></i> <?php echo __("Delete")?></button>
    </div>
    <div id="customer-messages-wrap" data-bind="scope: 'customer-messages'">
        <div id="message-loader" data-role="message-loader" class="loading-mask" data-mage-init='{"messageLoader": {}}'>
            <div class="loader">
                <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                     alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                     style="position: absolute;">
            </div>
        </div>
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#customer-messages-wrap": {
                    "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout(); ?>
                }
            }
        </script>
    </div>
    
    <script type="text/javascript">
    //<![CDATA[
    window.tinyMCE_GZ = window.tinyMCE_GZ || {}; window.tinyMCE_GZ.loaded = true;
    //]]>
    </script>
</div>