<script>
var wpwlOptions = {
    locale: "<?= $block->getLang();?>",
    paymentTarget: "_top",
    style: "<?= $block->getStyle();?>"
};
</script>

<script 
    src="<?= $block->getFormUrl(); ?>"
    <?php if ($block->getIntegrityHash()): ?>
        integrity="<?= $block->getIntegrityHash(); ?>"
    <?php endif; ?>
    crossorigin="anonymous">
</script>

<form action="<?= $block->getShopperUrl(); ?>"
      class="paymentWidgets"
      data-brands="<?= $block->getPaymentBrand(); ?>">
</form>