<?php
/** @var \Magento\Catalog\Block\Product\ListProduct $productList */

$category = $block->getCurrentCategory();
if (!$category) {
    return;
}
//echo "HI";
// Magento default product list block create
$productList = $block->getLayout()
    ->createBlock("Magento\\Catalog\\Block\\Product\\ListProduct")
    ->setCategoryId($category->getId())
    ->setTemplate("Magento_Catalog::product/list.phtml");
// Render the product list
echo $productList->toHtml();
?>

<section class="mb-16">
      <div class="text-center pt-8 pb-8">
                <h2 class="text-6xl font-semibold text-[#1A3764]">Trending Products</h2>
                <p class="text-gray-600 mt-5 text-3xl">See the Trending Products in this Category</p>
            </div>
            <div class="section-header">
                 <p class="text-[#141A25] mt-5 font-bold text-2xl">Trending Products vru</p>
                <div class="section-nav">
                    <button class="section-nav-btn" onclick="scrollProducts('trending', 'left')">
                        <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                        </svg>
                    </button>
                    <button class="section-nav-btn" onclick="scrollProducts('trending', 'right')">
                        <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                        </svg>
                    </button>
                </div>
            </div>
                <?php foreach ($productList->getLoadedProductCollection() as $product): ?>
    <div class="product-card">
        <img src="<?= $block->getImage($product, 'category_page_grid')->getImageUrl(); ?>" />

        <div class="product-info">
            <h3><?= $product->getName(); ?></h3>
            <p><?= $product->getFinalPrice(); ?></p>
        </div>
    </div>
<?php endforeach; ?>

           
            
        </section>
 